# https://www.bilibili.com/video/BV1XZ4y1S7e1?p=112&share_source=copy_web

main:
	gcc main.c max.c
	./a.out

main_intermediate:
	gcc --save-temps -c main.c
	ls -lh

# export MANPAGER='less -I'
# man gcc
#   -c: compile but not link, output the .o file
#   -g: Produce debugging information in the operating system's native format
#   -O: optimize code
