gcd:
	javac GreatestCommonDivisor.java && java GreatestCommonDivisor

download_jars:
	wget https://algs4.cs.princeton.edu/code/algs4.jar --directory-prefix algs4-jars

# download and put lib into `edu/princeton/cs/algs4/`
# https://algs4.cs.princeton.edu/code/

