// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcdb

import (
	"time"
)

type Movie struct {
	ID        int64
	Title     string
	Year      int32
	Runtime   int32
	Genres    []string
	Version   int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Permission struct {
	ID        int64
	Code      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Token struct {
	Hash      []byte
	UserID    int64
	Scope     string
	ExpireAt  time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID           int64
	Name         string
	Email        string
	PasswordHash []byte
	Status       string
	Version      int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type UserPermission struct {
	UserID       int64
	PermissionID int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
