clean:
	rm -rf a.out prog

dangerous_twiddle_demo: clean
	gcc -g twiddle_demo.c
	./a.out

dangerous_swap_demo: clean
	gcc -g swap_demo.c
	./a.out

benchmark_lower_demo: clean
	gcc -g benchmark_lower_function.c
	./a.out

