// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package data

import (
	"database/sql"
	"greenlight/internal/config"
	"greenlight/internal/sqlcdb"
)

// Injectors from wire.go:

//go:generate wire
func SetupModels(cfg config.Config, db *sql.DB) (Models, error) {
	queries := sqlcdb.New(db)
	models := NewModels(queries)
	return models, nil
}
