// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package data

import (
	"greenlight/internal/config"
	"greenlight/internal/dbconn"
	"greenlight/internal/sqlcdb"
)

// Injectors from wire.go:

//go:generate wire
func SetupModels(cfg config.Config) (Models, error) {
	db, err := dbconn.NewDB(cfg)
	if err != nil {
		return Models{}, err
	}
	queries := sqlcdb.New(db)
	models := NewModels(queries)
	return models, nil
}
