# https://makefiletutorial.com/#automatic-variables-and-wildcards

# I suggest that you always wrap it in the wildcard function, because otherwise you may fall into a common pitfall described below.

