services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: greenlight
      POSTGRES_PASSWORD: 123
    ports:
      - 5439:5432

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - 8080:8080
