.PHONY: interfaces1 interfaces2 interfaces3 fmt

interfaces1: fmt
	@go run interfaces1.go

interfaces2: fmt
	@go run interfaces2.go

interfaces3: fmt
	@go run interfaces3.go

interfaces4: fmt
	@go run interfaces4.go

interfaces5: fmt
	@go run interfaces5.go

interfaces6: fmt
	@go run interfaces6.go

interfaces7: fmt
	@go run interfaces7.go

interfaces8: fmt
	@go run interfaces8.go

fmt:
	@gofmt -w *.go
