.PHONY: interfaces1 interfaces2 interfaces3 fmt

interfaces1: fmt
	@go run interfaces1.go

interfaces2: fmt
	@go run interfaces2.go

interfaces3: fmt
	@go run interfaces3.go

interfaces4: fmt
	@go run interfaces4.go

fmt:
	@gofmt -w *.go
