// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package mailer

import (
	"greenlight/internal/config"
)

// Injectors from wire.go:

func SetupMailer(cfg config.SMTP) Mailer {
	mailer := New(cfg)
	return mailer
}
